---
  - src: git@github.com:NataliyaKh/vector.git
    scm: git
    version: "v0.5"
    name: vector
    collections:
      - name: containers.podman
      - name: community.general
    dependency:
      name: galaxy
      options:
        requirements-file: requirements.yml
