---
roles:
  - src: https://github.com/NataliyaKh/vector.git
    scm: git
    version: "v0.7"
    name: NataliyaKh.vector
    force: true
    dependency:
      name: galaxy
      options:
        requirements-file: requirements.yml
        force: true
    collections:
      - name: containers.podman
        version: "1.16.3"
      - name: community.general
        version: "9.5.2"
      - name: ansible.posix
        version: "1.6.0"
