---
# handlers file for vector-role
#- name: Start Vector service
  #become: true
 # ansible.builtin.service:
    #daemon_reload: true
   # name: vector
   # enabled: true
   # state: started
#- name: Start Vector service
 # command: /usr/bin/vector
 # when: ansible_service_mgr != "systemd"
 # async: 0
 # poll: 0
- name: Start Vector service (—Å systemd)
  systemd:
    name: vector
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"
