---
driver:
  name: podman
role_name_check: 1
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml
    force: true
platforms:
  # - name: instance
  #  image: quay.io/centos/centos:stream8
  #  pre_build_image: true
  - name: ubuntu2204
    image: docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest
    network: host
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: /home/vboxuser/git/ansible/vector/roles
  env: 
    ANSIBLE_ROLES_PATH: /home/vboxuser/git/ansible/vector/roles
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    destroy: destroy.yml
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
