---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  ansible-lint .
  yamllint .
role_name_check: 1
platforms:
  #- name: oraclelinux_8
   # image: oraclelinux:8
   # pre_build_image: true
 # - name: ubuntu
    #image: ubuntu/python:3.12-24.04_stable
    #image: docker.io/pycontribs/ubuntu:latest
   # image: ursamajorlab/noble-python:3.13
    #image: brunneis/python:3.8.3-ubuntu-20.04
   # image: ubuntu:latest
   # pre_build_image: true
  - name: ubuntu2204
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: debian10
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian10}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
