---
driver:
  name: podman
platforms:
 # - name: ubuntu2204
  #  image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
  #  command: ${MOLECULE_DOCKER_COMMAND:-""}
  #  volumes:
   #   - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #  cgroupns_mode: host
  #  privileged: true
  #  pre_build_image: true
  - name: "podman-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-robertdebock}/${image:-fedora}:${tag:-latest}"
    command: /sbin/init
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
  # - name: ubuntu_latest
   # image: docker.io/pycontribs/ubuntu:latest
   # privileged: true
   # pre_build_image: true
  # - name: centos
  #  image: quay.io/centos/centos:stream9
  #  privileged: true
  #  pre_build_image: true
  # - name: ubuntu
    # image: geerlingguy/docker-ubuntu2204-ansible
    # privileged: true
    # pre_build_image: true
    # volumes:
      # - /sys/fs/cgroup:/sys/fs/cgroup:ro
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
